export const mockListings = [
    {
      id: 1,
      image: "/images/listing-img.jpg",
      status: "For Sale",
      address: "9/5 Ocean Street, Woollahra NSW",
      sqft: "2137",
      beds: "03",
      kitchen: "01",
      baths: "02",
    },
    {
      id: 2,
      image: "/images/listing-img.jpg",
      status: "For Sale",
      address: "9/5 Ocean Street, Woollahra NSW",
      sqft: "2137",
      beds: "03",
      kitchen: "01",
      baths: "02",
    },
    {
      id: 3,
      image: "/images/listing-img.jpg",
      status: "For Sale",
      address: "9/5 Ocean Street, Woollahra NSW",
      sqft: "2137",
      beds: "03",
      kitchen: "01",
      baths: "02",
    },
    {
      id: 4,
      image: "/images/listing-img.jpg",
      status: "For Sale",
      address: "9/5 Ocean Street, Woollahra NSW",
      sqft: "2137",
      beds: "03",
      kitchen: "01",
      baths: "02",
    },
    {
      id: 5,
      image: "/images/listing-img.jpg",
      status: "For Sale",
      address: "9/5 Ocean Street, Woollahra NSW",
      sqft: "2137",
      beds: "03",
      kitchen: "01",
      baths: "02",
    },
    {
      id: 6,
      image: "/images/listing-img.jpg",
      status: "For Sale",
      address: "9/5 Ocean Street, Woollahra NSW",
      sqft: "2137",
      beds: "03",
      kitchen: "01",
      baths: "02",
    },
  ]
  